### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by egordorichev** [egordorichev/LastTry#6]
Moved todo list to trello: https://trello.com/b/X3o5KsSG/lasttry-development

- [ ] **Swing sword**
- [ ] **Z-index for the blocks and entities**
- [ ] **Main menu and World Loading states**
- [x] ~**Entity Manager**~
- [x] ~**Move back the biomes**~
- [ ] **Player saves**
- [ ] **Finish `Tool` class**
- [x] **Eye of Cthulhu** (in progress)
- [ ] **Slopes**
- [ ] **Spawn and spawn rate**
- [x] ~**Make player able to place blocks**~
- [X] ~**Enemy drops**~
- [x] ~**UI**~
- [X] ~**Inventory**~
- [ ] **More blocks**
- [ ] **World generation**
- [ ] **Chests** (must finish GUI first)
- [ ] **Multi Tile block** find a way to store them in the world
- [x] ~**Crimson and Corruption world property, also expert mode**~
- [ ] **Rotated hitboxes for sword and other items**
- [ ] **Hit the player on touch and delay after hit**
- [ ] **More tileable blocks** Blocks should tile to dirt. And also, fix this: 
![screenshot_2017-03-16_11-13-45](https://cloud.githubusercontent.com/assets/7851390/23987308/fe13c1d2-0a39-11e7-8327-89573cdcf5a6.png)
- [x] ~**Update textures**~
- [x] ~**Remove `LuaMod`**~
- [X] ~**Build status**~
- [ ] **Lighting**
- [X] ~**Update movement methods** so that any one can move up and down, while flying.~
- [ ] **Multiplayer**
- [X] ~**World Time**~
- [X] ~**Hardmode world property**~
- [ ] **Projectiles**
- [ ] **Make the sand fall** This requires projectiles
- [x] ~**Save time to the world file**~

And more to come. Feel free to post more in comments.

**Comment by Col-E** [comment]
Worked a bit on enemy drops in pull https://github.com/egordorichev/LastTry/pull/10

**Comment by egordorichev** [comment]
Moved `EntityID` to `EnemyID`, removed `isFriendly` field.

**Comment by egordorichev** [comment]
Lighting

**Comment by egordorichev** [comment]
Also, we will need data folder in users home. On linux `~/.LastTry` and so on...

**Comment by Col-E** [comment]
Could we alternatively allow this game to be run portable? So for example running the game off of a USB drive. Instead of requiring the game be in the `~/.LastTry` directory we could have paths be relative to the game executable.

**Comment by egordorichev** [comment]
Hm. You mean creating a folder with data in the folder, where jar is?

**Comment by Col-E** [comment]
I mean that files are all just relative *(Like how they are now)*. So for example if the game path is: `D:\Games\LastTry\Game.jar` the world folder will be `D:\Games\LastTry\assets\worlds\`.

**Comment by egordorichev** [comment]
Ok. But we should make folder hidden. And also, maybe we want to pack assets (textures) into jar, so people can use them

**Comment by Col-E** [comment]
I don't see why either is necessary.  Why should we hide the worlds folder? As for the textures they could just open the jar file like a zip file.

**Comment by egordorichev** [comment]
Ok, but they can delete this folder. SO we need to make sure it is in place each time, we start the game. And maybe host assets some where for backups

**Comment by egordorichev** [comment]
And also, first time player runs the game, where do the assets come from?

**Comment by Col-E** [comment]
Could always check files against the repo.  Lets say the `Box.png` texture was missing. Just have java download it from:
`https://raw.githubusercontent.com/egordorichev/LastTry/master/assets/images/Box.png`

Not the ideal solution since the master branch is subject to change but better than nothing. However I think making sure the folder exists and such is not something worth worrying about right now. 

***

I think for running the game we make a zip file like this:
```
├─ Game.jar
└───assets
    ├───fonts
    ├───images
    │   └───splashes
    ├───mods
    └───worlds
```
Users extract the zip and double click the `Game.jar`. This would perform just like if we ran it from an IDE. If the user deletes something they can just download the zip file again *(Or check their recycle bin)*.

**Comment by egordorichev** [comment]
Ok

**Comment by egordorichev** [comment]
Working on UI:

![screenshot_2017-03-17_11-34-49](https://cloud.githubusercontent.com/assets/7851390/24035316/297c4390-0b06-11e7-9f47-9ac0c8ec0d33.png)

**Comment by egordorichev** [comment]
Inventory works now!
![ezgif-2-6c44877a48](https://cloud.githubusercontent.com/assets/7851390/24046755/b31c155c-0b34-11e7-9aa1-5143c9a25462.gif)

**Comment by egordorichev** [comment]
TODO: slopes

**Comment by egordorichev** [comment]
![screenshot_2017-03-18_10-05-14](https://cloud.githubusercontent.com/assets/7851390/24069841/cb788890-0bc2-11e7-978c-2ffec5e76776.png)

**Comment by egordorichev** [comment]
TODO: world time

**Comment by egordorichev** [comment]
TODO: spawn rate

**Comment by egordorichev** [comment]
![ezgif-2-9c0f183273](https://cloud.githubusercontent.com/assets/7851390/24079067/2c3df52a-0c90-11e7-8d98-94c7159415fd.gif)

**Comment by egordorichev** [comment]
TODO: make the sand fall

**Comment by egordorichev** [comment]
TODO: Main menu and World Loading states

**Comment by egordorichev** [comment]
![screenshot_2017-03-22_15-52-37](https://cloud.githubusercontent.com/assets/7851390/24198715/ff0a10a4-0f17-11e7-86c4-4d5882105170.png)

Working on buffs

**Comment by egordorichev** [comment]
![screenshot_2017-03-23_16-27-31](https://cloud.githubusercontent.com/assets/7851390/24249895/f7f0327a-0fe5-11e7-9d25-bc27282afc98.png)

**Comment by egordorichev** [comment]
![ezgif-2-d8aac864a6](https://cloud.githubusercontent.com/assets/7851390/24287511/17fe2f72-108b-11e7-9820-4229275f4c28.gif)

**Comment by egordorichev** [comment]
![screenshot_2017-03-24_12-34-35](https://cloud.githubusercontent.com/assets/7851390/24288487/a16f696c-108e-11e7-9cfc-47dc176fcd87.png)
Playing with light.

**Comment by Col-E** [comment]
A re-work of the world class broke the dirt-grass texture merging. Pull-request [#28](https://github.com/egordorichev/LastTry/pull/28)  has [brought the merging back.](https://my.mixtape.moe/yrbkin.png)

**Comment by egordorichev** [comment]
I'm thinking about moving to the LibGDX...

**Comment by egordorichev** [comment]
Yes, thank you! I've just disabled it, because I got a bit stuck with the textures...

**Comment by egordorichev** [comment]
![ezgif-2-a3fce9c683](https://cloud.githubusercontent.com/assets/7851390/24333639/5af896c0-1264-11e7-9743-ee7214bd8498.gif)
The evil now can spread! Not to smart, but it spreads!

**Comment by egordorichev** [comment]
![screenshot_2017-04-01_18-54-49](https://cloud.githubusercontent.com/assets/7851390/24580215/12d77f5c-170d-11e7-8016-1a4b19652b58.png)

**Comment by egordorichev** [comment]
Moved todo list to trello: https://trello.com/b/X3o5KsSG/lasttry-development
